# Generated by Django 5.2 on 2025-05-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapplication', '0004_quiz_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
