# Generated by Django 5.2 on 2025-05-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapplication', '0005_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SC', 'Single Choice'), ('MC', 'Multiple Choice')], max_length=2),
        ),
    ]
