# Generated by Django 5.2 on 2025-05-02 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapplication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score achieved by the user, calculated after completion.', max_digits=5, null=True)),
                ('completed', models.BooleanField(default=False, help_text='Indicates if the quiz attempt has been completed.')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user started the quiz.')),
                ('end_time', models.DateTimeField(blank=True, help_text='Timestamp when the user submitted or finished the quiz.', null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizapplication.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizapplication.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizapplication.question')),
                ('selected_answers', models.ManyToManyField(blank=True, related_name='user_selections', to='quizapplication.answer')),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
