# Generated by Django 5.2 on 2025-05-02 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizapplication', '0002_quizattempt_useranswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('video_url', 'Video URL'), ('pdf', 'PDF Document'), ('external_link', 'External Link')], max_length=20)),
                ('content_text', models.TextField(blank=True, help_text="Use for 'text' content type.", null=True)),
                ('content_file', models.FileField(blank=True, help_text="Use for 'pdf' content type.", null=True, upload_to='learning_files/')),
                ('content_url', models.URLField(blank=True, help_text="Use for 'video_url' or 'external_link' content types.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_content', to='quizapplication.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_learning_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Learning Content',
                'ordering': ['-created_at'],
            },
        ),
    ]
